# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63c3d862155a538fc1584677e611f8050d500d41b68420f32d508f94c0490722f715bb1da4089bd2506761574701ecd427b2298c97a394becaab7cef0a165754

test:
  secret_key_base: 842b675d0ec14b7e3bbde8ac9343ba9c91ea91f6b3a207618a53dbd503bda5b772acc12ebbb3dd653fce2735f04efa8001259809b698c5a1921ff9ce7d3325f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
